image: busybox
port: 8000
command: "printenv"
limitCpu: 100m
limitMemory: 256Mi

env:
  CAPE_ROLE: DEV

secretNamespace: deploymentexample
envSecrets:
  TEST_SECRET: AgAWntccL0jQ2hQv9MJj2yFT2f8rnjxU14bbpQHDfCvasWK0EPTZ7MdiFqvKw7Ic0OTA6a6Usuh/UxzGLgr+41Uzv/4xtmw8c6QiP3i0/C6dr74rq9iGv7c6bFFJ678epv0jgCL9m7efffmKRjmrnE34c1g/BEbGIneJqlNB5HfYjwzvXlFJ8LgUcMivQ3w8eXhZ/vrPMm0KjO5XLzsoRVfcOcJ/XP4l28VO/9QKZDb/1OJAhGwOLsRdyyBhJZ38fsdOQN6bpH0cmXTjna1D2Ygwy7QoCBJphHttRRXBtJ8DZ06fsYPC5ckTrsfUEowAZNKqNCS2H6A2N0Be168BN25+bUSJnFps1gDeflXe4Pd0jgoLOvaYvmQ+W5hjm0K9AedS15ffV+d0Dpdc3A+PO1ZBm6AucBDtlAA7FarqvAS+8gnBUOqcafnbaQlmjFfg0h7JIJwzvP2jNV9ZUHUwLNhq9tv//YiqjuEk8KUYzpTw/HAuywznbIcs823zVEhuMADzdeeDfcWq6qxiMMMOiadE6hCmIBr1Z6OryhL1/2mPQxLe0glAQIC9Z4tcejvQ4at9t4AQJeEF0+xUjIqF++ih8mQ8E7+1fi1i1/MD71Xd3WZEITWT14D6ksR859rt5zD8/K1JQNal6w+Duvjx0QdEp06TSwJiJJQy6Z4dUJOFXaMWaMt5yrGlWkbXFsZcD0LMKEMG+KWuOzJYe1DzmRSZP0uNSRqKjf1IVSIGmg==
