# bare minimum values that do not change
# simple (non mapping values)

image:
  repository: busybox
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

port: 8000

command: "printenv"

limitCpu: 100m
limitMemory: 256Mi

livenessProbe:
  path: /livez
  initialDelaySeconds: 10

readinessProbe:
  path: /readyz
