image: busybox
port: 8000
command: "printenv"
limitCpu: 100m
limitMemory: 256Mi

env:
  CAPE_ROLE: DEV

secretNamespace: deploymentexample
envSecrets:
  TEST_SECRET: AgA5oZn9mx1+tQbdesA5ONJTQgjyJUz6zn6VgoUJdQM5zn5eH/ezbnDkghBu7b9EIkh1cpf1+wNTOGeTQl1IL0nvgIgWX8iv7i3f0cx/bUR4a0ccxKIuWjLpzC/QVjqI4/IF0jCTPBiBOvTzAeOYX/pI9yGq/SVS17KLn9nfsEkEcPQOBMYftf5Vcgo1Xtq8KPQ99Da8MAH4pgmdn0Xw2ir/iRGTAT6uzWo5g+DpuK2SesZGVz4vAYvpcUjS3x6mds+M2HQxsApogGKW3mmp1kkr1nyfDR99NmC7CXZLJYEx7C6ANVTwvz9sUAjbmC4BSyQNeotdEDOBnOrftTBNLysF30UFO82mEou2YnBqsBvC5/bF0+uGfElQ1VYYitz2dXGqkcGBy9bQvAL0fBS7gvbwLVwTKlZjbACLj3Zf5vq8ICwhI9M4EpHfwo+SkchhVORmNALMNEOi9HBTm5c2OHRQfiJH2AtMFVO0kWbk1ldPfJfOIZMfGX2eHIDAA9haxJn58755Tuke7OPlcB38DG0+oSefBXLBoAV+e5SlKmyLMwHVjp/hgd+a4Q5gEV3vCnkVcAe8yLlSvJ7dVlZ9jgp2VOKaE5jQEzo5RJaDdWlWEOZRzRorcZrP9DQF4joxXzMPn+En34IoTSMyiZdVkBixyZBxLZO++5CY2lO5uc3eyKClOfPCbbRA6R9IMl0hoPauqJVV6cHPyTiB3erJt9f9NC1KQNNivD74+b/TLA==
