---
# Source: aruba-uxi-example/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap02
data:
  hello: goodbye
---
# Source: aruba-uxi-example/charts/aruba-uxi/templates/application-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
    helm.sh/chart: aruba-uxi-6.0.1
    app.kubernetes.io/managed-by: Helm
    repository: aruba-uxi-example
    namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
---
# Source: aruba-uxi-example/charts/aruba-uxi/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  labels:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
    helm.sh/chart: aruba-uxi-6.0.1
    app.kubernetes.io/managed-by: Helm
    repository: aruba-uxi-example
    namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-service
      app.kubernetes.io/instance: aruba-uxi-example
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-service
        app.kubernetes.io/instance: aruba-uxi-example
        helm.sh/chart: aruba-uxi-6.0.1
        app.kubernetes.io/managed-by: Helm
        repository: aruba-uxi-example
        namespace: default
    spec:
      containers:
      - name: webapp
        image: aruba-uxi-example:latest
        imagePullPolicy: Never
        env:
        - name: APPLICATION_NAME
          value: "example-service"
        - name: APPLICATION_VERSION
          value: latest
        - name: ENVIRONMENT
          value: "dev"
        - name: DD_ENABLED
          value: "false"
        - name: DD_ENV
          value: "dev"
        - name: DD_SERVICE
          value: "example-service"
        - name: DD_TRACE_ENABLED
          value: "false"        
        - name: DATABASE_URL
          value: "postgresql://username:password@db:5432/aruba-uxi-example"
        - name: DEBUG
          value: "true"                        
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: readinessProbe
            - name: Content-Type
              value: application/json
            path: /status
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: livenessProbe
            - name: Content-Type
              value: application/json
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
