---
# Source: aruba-uxi-example/charts/aruba-uxi/templates/application-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
<<<<<<< HEAD
    helm.sh/chart: aruba-uxi-2.0.1
=======
    helm.sh/chart: aruba-uxi-2.0.0
<<<<<<< HEAD
=======
    app.kubernetes.io/instance: asimmetric-example
    helm.sh/chart: asimmetric-1.1.7
>>>>>>> 0ae6f5e (adding a legacy ingress option to applications):examples/asimmetric-example/output-local.yaml
>>>>>>> e808a23 (adding a legacy ingress option to applications)
=======
>>>>>>> b9224f7 (rebase fixes)
    app.kubernetes.io/managed-by: Helm
    repository: aruba-uxi-example
    namespace: default
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
---
# Source: aruba-uxi-example/charts/aruba-uxi/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
  labels:
    app.kubernetes.io/name: example-service
    app.kubernetes.io/instance: aruba-uxi-example
<<<<<<< HEAD
    helm.sh/chart: aruba-uxi-2.0.1
=======
    helm.sh/chart: aruba-uxi-2.0.0
<<<<<<< HEAD
=======
    app.kubernetes.io/instance: asimmetric-example
    helm.sh/chart: asimmetric-1.1.7
>>>>>>> 0ae6f5e (adding a legacy ingress option to applications):examples/asimmetric-example/output-local.yaml
>>>>>>> e808a23 (adding a legacy ingress option to applications)
=======
>>>>>>> b9224f7 (rebase fixes)
    app.kubernetes.io/managed-by: Helm
    repository: aruba-uxi-example
    namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-service
      app.kubernetes.io/instance: aruba-uxi-example
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example-service
        app.kubernetes.io/instance: aruba-uxi-example
<<<<<<< HEAD
        helm.sh/chart: aruba-uxi-2.0.1
=======
        helm.sh/chart: aruba-uxi-2.0.0
<<<<<<< HEAD
=======
        app.kubernetes.io/instance: asimmetric-example
        helm.sh/chart: asimmetric-1.1.7
>>>>>>> 0ae6f5e (adding a legacy ingress option to applications):examples/asimmetric-example/output-local.yaml
>>>>>>> e808a23 (adding a legacy ingress option to applications)
=======
>>>>>>> b9224f7 (rebase fixes)
        app.kubernetes.io/managed-by: Helm
        repository: aruba-uxi-example
        namespace: default
    spec:
      containers:
      - name: webapp
        image: aruba-uxi-example:latest
        imagePullPolicy: Never
        env:
        - name: ENVIRONMENT
          value: "dev"
        - name: DD_ENABLED
          value: "false"
        - name: SENTRY_ENABLED
          value: "false"        
        - name: DATABASE_URL
          value: "postgresql://username:password@db:5432/aruba-uxi-example"
        - name: DEBUG
          value: "true"        
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP        
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: readinessProbe
            - name: Content-Type
              value: application/json
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            httpHeaders:
            - name: Host
              value: livenessProbe
            - name: Content-Type
              value: application/json
            path: /livez
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
