aruba-uxi:
  sealedSecrets:
    imagePullSecret: AgC+shUQi6hleq7w05Hcc+Rqjd301LiyLTxn3IjcRac6zS6l5S4f/aonP2iFEff1vN113wTaNoTFbNbHFuklE+WQ68A6cMeyuTe5BlLr0z6d1O8rmuiJrsuHLAq5nzVjlZvf9Kgn0a+OIEYumd6UPKqIyAagIKSiKy+KKMx8j61t3dnlroI7ckapp7NQlvOOZ+onJlOaqF9ahowJ6dDwpWfZKKUm8Bt5W+I3xj9zODh7mMioAo4Snvv4uXD/9QlLzMYJxRFekxEe//F3dquqWBKqeKVYm9rmlpRYopoftT0u9VKLM0EfrWURPv9jSGF4XCqS5rRJsn4URV7gskDkGZr5K/6iu4WGJhRC1+5xdrCMU3/i4AQRaZn3DrqroGWYRW1M2foFhWsg3z8aQkNEeCiBSqfMAycC/nw51bnvGwjglpbm9wHqHtvG3dV9JDQsVlluiEtroM7BsLjMYmx0q7U7WWfzLsiXevJJjBkVHyFq/3Og/5EH23jF3SEdchzInbjjpuBNIETKHGm5wRyTaBve1RA+DstYUWRwB4pFodknT45JuG0r0JLk1hsf5IjRDNam+AlYw0zIJ27vr1hDLjAIDq4wHGc2QO+u0kbL0pXPRtBvrvBlhHT8m7F/Haw/Nt/1URlJ/+HpL5YGsXmZ25J4aHBF3kw8rX9JQGuNS3gfSNP99AvDl5taNeXmzzssJqg8gekcBCjmR5uOSxdtFYUZfhxc4y2fC2dhUeL0O3Q3XytEdJyI70RLg5uKowtokcmqklzXYEeRtOqksV5z2carDqwY+Zk8sJRUWY0gUgVUUo/PtPK4jgrM7saKaj1IYHh/59SNxbpAvV7QzVuExOuqhBVx02s89aMq0GxnRzgH20U3996qBs1DUtrEt9rPio8wNPhN9T7tAK4qytivUgqHmiaV1csrXeXYaWHBWGuzGjyYW9vip2dCkZbZCwdIdx3Mox2B
    env:
      aws-access:
        AWS_REGION: AgDHInk7E4j3jC8zuBrfDirC4bTlUj4nEUk7bnPX8krFC4kWGELObhvcKb2xDkE6dAw39eeAbBUuZXmXq8Jsk1+donH3SZP3BIwng+fjjdCJjKn8Cs/CjNPzH5zvAzpS/GDik5wGCLhaYn9dAe0DXXnq9pRxypjAyv3fAMs3VSMP4pOEzGvBkoqHwzEBXMy+6tGrZepn6RX7sBXutUcg2sl9NUPcfMLC1SrfvCluzqFM0vqSwnyL7QYbjUkCLFh192H4a0LFoV068w6K/rZTMVG5MLXgBziB24lAT0MtY0u1r/xIW1t8PoQuDegcUfr0Cmj5zJI3F7WFn7EoG6qy/2gemO+X5Kzmr28v02t7UiXaBqqWxXU7LsvdUjQ5SGGtOlCeVOXsnCGnBzhVSFPKxRMh3aLKeoRieflnYBQQhEyIAsRA2YY1m6V3rCLAVecnA7NwlpbVOVqCqBTdEj5wI/KsF3GcnUZQ+ceftLHxDPgawLZW5DCeQROF1mR1LxVmJuSb3Aaci8Fc9szusFSto7vz0RhKX2wCJMKf7gTKOSfdUnHc1cw7IG4FjZbA4DE5nVE7LXkPcEXe0dEJ+uUk6a+O+APi20T+dU2p5WiH6W1EjVjLQz3zcR1oKw264uI9iX6Rt/pfudWtR2pmLacUcu5HkEFRqnvpek6qnXUSF52YlEfWgWLbqME2pcoYQJ2hRt2rf/8g0cd3kJPF
        AWS_ACCESS_ID: AgCiBP+jM76iL3njeCm0Ndoj7gvVGhqAluKGevJd7WvbUh+do+SAEFUL+SRlva8rep6YXmGhXsdLG9DtfPtM8YR6L7wvQiDLfVaUi0pcdJf5c6EA5VqznAr7UrMnMratln/TKvUbsLtaPcjwg5jVG0rY4SDCzdmPnzekXChK8AcKAcggm6OA6ITvUfJF01G+kP+e3JvUzEMebT95Cm0E6mdS8GaxTSTZdzEkTOTuPnhRwIvCZZM3Ixha1Ta12U5bXKiWY7BRIXy2yzB1Ck0iEtzA57I1YsxzikY8uj4IXyt/ETJyGt5bp2ezwFzdZInw+/KeuJ8+4/PnDtINnUftQq5VRgcRL583TDnILyk5mcowLwMITYkZVgS3y9rzHcMyQT2UDeF/5g7lQDPWIAcc25DpFYqQxmI+Ud3gmlcXIuGrntb9SwiWIYzmmZD5F85UZCpEfvKcaT761upxgOpMAAt7q19M3MXGB/0a2B5nhCpLuGfa+WbXjAeGeGhSgjLGbHJzgkT7ZGEJkUHoh4mfOTw9vI93UNN2V5jCUuFelEA8+UAZQpVli8Qr4rKrEdnGttYxFzvFVfp/IfvyuXc4ArndzfLu4BZHYqDzh3Qz8pHzx0syFDUHjC7pnjByDGE1EgQyVdp8Qbule5hd1TklRAAbOZE02qrePOkTFULLNpHQ0DkkGuELSjcBJfrQtq73QGSrO8BdOuej5LI=
      database-url:
        DATABASE_URL: AgAuvJH6oRC1EklejbecyiSvse4HcCn/VqZcZectp14ZKp/fZlekWVWMQR9eBmXGr4QIfgbMeDNdMXfh+3g2GaXSA+8z2gNTQQWqweyy9WBnXyOG6uJD/yFXXz1mIACAektFMUNqAIDGTIUahcdGwCtRqUaq7ikOyx0HWo6ZtTE2DKYvRUZG8226pm6s4HQNW9aMwgpsmrZYZYQUOiO5yFeuUA/CdoxkzK6G7ArtQj2dRXKRH5p4/foBvXZpVTegWu2ATnfEJf+VVs0jNpAoDk5+shg5grH8GHTD/COmf8SCEdiKk6HZhWof8di+l+l9eTx+1rcAuMPZnNvOuW8G2b8Cb4V71vcg5O3ONJnyLcSW0mL4o66qpK+z3DBZq10r3fnMEWBUVnDdzZcUDWs6UoVjj/rBleKzLGNkbRTqvXbzqdxbjq1w1yLHQMw2WzxLfARwM08LOT91C2egL7RyjBjBSM/TjPzMzMzZkbu7U0d46GVI6/H3mPOc831o5cLncBjxph6Nx/mrS/NA6Nai56OI7wfXK5cIYJKX+Ch47Qewj80CZjHnud8n2aZqrsk4nAp+ZX6yAThQIq8ytg21oZYwOcTSbBfwlzEqjJP5jBMzIIrxauXsHiIAjcjpaQ40mkFI7mJpwGgcxPMtJglC29yDTdRctakht2EMXs7r2GO5llI//nOzlheq5PnstyaoiwPMO47ebk+MRXNtxiUxhHmXeeLXe7ZKkHegKERTrPYyZCjY
    secretMount:
      example-service-account:
        example-service-account.json: AgCF2ON/DjK0uf8WKIxTwSuVHDdsFVfHqR9pHrj3htxPDo5ePpJYpfFGzcDBLRzcBOCMZq8I3Z9gUDPXoMPZb+aYc76NTNQxzG/NchS4aekTy3K2FiMiTKS9lzz/WI5CvNXhFoEb06uHy6DR8DbzYn+S+cGsOjlNnU6HvZdn8rqEEGC151IhT0FPVQaiPV4PJkXgHuYCKoCUhsgK80pHsWr8AaUf3r3McbcSYC1eXYVaoy6uhbFsMqZHNOenOooMUsl0xJZ1i/RueKiind9URIKTSxDLG5xEDu5isZgrP22xxzZ1HEolMc+UmtPwDHqr90+Dmnto8vOlLnVN8Mwlj78AZe2SjVp39QRtouKKjKPvNacfSoVkHroSssDLnW3gtucBAthzDe1gAitA0xWV02TYbYnpHcFmx18h1b3UBEmZyfzdtpsU/4oDqNCa1zzL/rBjK4slzTlPvajRgP6GdW+311tOE+W7V2cvwro1u/lqX56dDMp+qLm2SAYAVBGsvbUPqxrcHhD9MMm65HrSU7IBtSqk/91KGtxkrC1pTtVHsav7xlgE9Azv+6iViJ70sTsLbA+4et/jKvu7cHKoLNR7UZ5JINnY1SR0rI8cBIBgvhHq/iu0a2y7eM3LmrFhVYpsM0PAaDeDg4Y0o2XIpF1i0wXBrrZaFLInbUN4Z0uj+MD+k37jDBsSx53JqKrph5qiHvdifZYh8gZ+IfFWNjg=
  global:
    environment: STAGING
    image:
      repository: quay.io/uxi/aruba-uxi-example
      pullPolicy: Always
    env:
      DEBUG: false
    envFields:
      HOST_IP: status.hostIP
    labels:
      global-label: global-label
  applications:
    example-service:
      role: webapp
      image:
        repository: quay.io/uxi/nginx
        tag: latest
      revisionHistoryLimit: 1
      replicaCount: 4
      serviceAccount:
        create: true
      port: 80
      livenessProbe:
        enabled: true
        path: /
      readinessProbe:
        enabled: false
        path: /
      configMap:
        - name: example-configmap01
          create: true
          annotations: {}
          readOnly: false
          path: /app/config
          data:
            config.json: |
              {
                foo: bar
                bing: bang
                server: {
                  host: hostname
                }
              }
        - name: example-configmap02
          create: false
          readOnly: true
          path: /app/config/example-configmap
      secretMount:
        - name: example-service-account
          readOnly: true
          path: /tmp
      env:
        AWS_DEFAULT_REGION: us-west-1
      envSealedSecrets:
        database-url:
          - DATABASE_URL
        aws-access:
          - AWS_REGION
          - AWS_ACCESS_ID
      labels:
        example-service-staging: example-service-staging
      ingress:
        className: internal-gateway
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            location ~ ^/health/(readyz|livez|status) {
              return 404;
            }
        hosts:
          - host: example-service.internal.staging.capedev.io
            paths:
              - path: /
      updateStrategy:
        maxSurge: 1
        maxUnavailable: 1
    example-worker:
      role: worker
      replicaCount: 0
      revisionHistoryLimit: 1
      image:
        repository: quay.io/uxi/busybox
        tag: latest
      command: ["/bin/sh", "-c", "while true; do sleep 3600; date; done;"]
      sentry:
        enabled: true
        dsn: AgBsCKUK1LVkqXFrIoqKHzUPCpH0cm2QomH5/d4f+ZgwaBBTKAOmOo0QBZz90BgJDAk3EwArlAw7EgACDkrbVJzHYofs/peFUvB8JO5jYZDjL5HnJ9Uyj1upE1/tBCZhzswKs/WIesRHZKseDgLSmE7//z8F9obVAKn6ECYMB4nhazfzJivDTRsbGZrgb0u0NDFdHRUhpNeBmclrheatz/ZtUL1Vbyvne1zQfRvBz7pGhzxLFFk/q5O//UmqAAWy6WRm6u0mWbvDM8CUmCzPkIBH4+pTuAT+2u/pbSrUGMKf9tEw5brqySPg7c/+jcaJUMY3cCNCIMxf9Zb83CuhqIggZpZfNBaGaYHiAU4BGELCEnk74uW/09A5/Qu1vY7wZYrfMJn3RTz8+jmXGxVyzmPzPyL7veOJwX2ajhRBbUQOtExcd2AFiMwbb3elgGY01rFuxvujq2ppqymGlkwjetWjQWUfKZ91CnBEEfnOz5PWnevoaN7acFzP2aRp7/qpZhN+mcl1jXp0ESVP3BptD8fhNdsnhpEra8dVZLJ2CXGXP+ubZUGrbV6kuccGwkg12dZjwBHYIZQ8akZNZjYRD+x6V6tah0dyVcedJgk7Zlx9mreCg9zW2ZQGL3Bhcjw9ZoxQTLkhWA6zodWxot/n73WIAsQfHYw177VJB9xWnPhZFolgS3iPkRHTalteSvBBsvRmNm8c052CzBY5uhaZp1ugjw==
  cronjobs:
    example-cronjob-producer:
      image:
        repository: quay.io/uxi/busybox
        tag: latest
      schedule: "0 * * * *"
      suspend: true
      command: ["/bin/sh", "-c", "echo Hello from the example-cronjob-producer"]
      serviceAccount:
        create: true
    example-cronjob-consumer:
      image:
        repository: quay.io/uxi/busybox
        tag: latest
      schedule: "0 * * * *"
      suspend: true
      command: ["printenv"]
      args: ["HOSTNAME"]
      restartPolicy: Never
      envSealedSecrets:
        aws-access:
          - AWS_REGION
      labels:
        example-cronjob-consumer-staging: example-cronjob-consumer-staging
