aruba-uxi:
  sealedSecrets:
    imagePullSecret: sealed_version_of_the_base64_encoded_dockerconfigjson
    secretMount:
      firebase-service-account:
        SERVICE_ACCOUNT:
          AgANJDTfHCNw1znybLcl/ySQTXawfFY1a1JENVEskd0jSfbj8ZJ5mxeWsIhvhYwuhEcLLHB7QEjsAQ7yKA9OjhqxjoH3JF4b/9GEqX/cqJLwqioVNVUFyXbLMEcNxIb/5qglh1FnNfEIOYSC9eiwIvAZq3mCvLBLsnJI9vIeTnqlDjtT/8BHxe7hJ8vRoGIrMx6T/+eE4Znq7HEMLpEf6nD46If1WSGcwLuJWLv2AHw/gfL+/JejrUbFLwQn4xxSNAsrzaSxhFLtLYASWlho+LKdok4ACY29jlzrVHAUXr2hl8JxW+vRvwXJ7mPAefviVlVidBqV2G2cy3aOXxWw3Libp38hqvTZqpUm9EtXsrJgOZ6X8e7NN/OoVVPlxko3opPkbEZrXA7TLOJZYulE2RNOn6o69Es1bihF6qTIF4MvS4idCd+HcCWLsHoGfWJiPE7/JOR1+YJ3V6XQelOvencYXtjhMVf6zTwwnatCIqZ/PSdr7gZwe/d2QBKTsCnlnJTqzcDEz/4qT53FWc2C2F2/jiXQrokPVndohnvakuezM7YX1XRYq3wUm/GU0aLxFlZ/ZEjiWPxUzlldT7O/shH4uFYIG+7OqRZ5MBjYdvMTE9QH8MaKksW6YOH2xVTw8gOyUjJ8ivUGZu8UtUwqYENJ3Jf6LRTIy3jL0hHGt0NkRul3dVRoRj6Y9EvNiV+PaomEmN753H+yqaWUI2COhBiONY/pBHMinn9wh16iSCEffpqOf8strv2CKykcqu6D591VGTMwJVPJ86m6AgLJEpe99NBTyyPstqIMWef9okp0ifEKLmbkluS6Ns3EAnL3UFg5N6MkrR5AEU/P80ZtidPEvNgHkMhXLYrK9iQfO1hHukUqd+MXwwCkb+WAxsga9vZnbEHvk5iM0Br52ayDN+jKe+pY4qcDUdZDXgBL7SD07QTiJ43KBiGEo2Sw7vLlyS7LFlhEYidR0ES6aWtB/ZOMhOmMZz8QjUgsU89DsiH80PkNRLl7ztJLSEsbeazKYzmCsFHSB9MT76rH053e+gV+HFJ8yQvCxz4s1aw/CrDBqxaxaDPJQSCGb3PG1rYC036k54qWUT9L7YKQfjKKO2zBWGeqeMfbzPkHh5U4Dm0/yTY2jfIYW2goRwQLzkd7R0E1wvX+O80q2eTEHnfwoTR94XOnaYBDdw9Zkl1Bfb2UunVriIbUkeWTmYtnpVpq0WMu/2a7w20xLTe45CaNZEt7LA7unHKCq8Aq2jfaqizzfKqqWiFe2djhbnGsM6sHl4mKZZSK3chtBQ10rhfjItOz2W/7Mi1TXA6D3vALypvMhjNcvq0nqKrIbYVDq5o5XoowOzcP4vGBgXHwGoB9nuZW6H5lujzhKKYtfSuW2vMOrm7rpAsyJZrLCIMHpB/DXej6Li7NumvAtG8fbo3sFrKRXKEo4FOM1hzMdAmZKqJsf26iLG5HgIsjvGuoNaXhl1Ak7s/iGig43GydfaCcHMyX9uDnibPaj7qJF0/b2ekZCJKPiPB7+Eqr5bQmFHCZd4jnL4ufUGG38MWYRB93nitJwOc00zmvpFJPZfno4iOW7OK9gsaSFWAsJ7Oy+GJipQWHRp3KNfxDvQvQuZWKiNy1IO0AjRcsU6fyXJz0zwr3DBwPEC2Ni2naTHxzGCcq/quYNzrMVmzgWxy8mhN8X6Dv5vePf6Fb2IltFrkB42p89Oo5wbHClk4ahgx9cFM7Eitjs0rEVCRfm06EJA+m98RPMOeCOQ/Fc64KPJivWI3gGZdQcDivWW3k7Eu3WiFnXhhoDaaYSaq6NUaUK83suEpJEWAGuoKQGiim3VIkc2RYtLkshmBBm8IBvt5ejbk01x454ugvfgyL5a9D9uOqp3SLG7kdIkNIMxC51ASPAX08VVvXF04mO6SHbl/GZPO9Qj5I/w2b5eX0NgZ0tCOHzbT27vmQMzsTeRvOgVD92FsrmHp18ZOSbfRp6uR1W0sfEL63o/KtLmhs+aUSC9i+LQ3GBz0em19Qv8/ezOtT5yiSsPOx7odwPU3j7vF2BSmj7CkPfSGnu0Jr7dhOaDkg+2gMUQQy7YZ2BHgbmNx+NO2xUK574D2mYWE8ostEHvlyPePCHGhOtMZ5variIl3H2eAY7sxM+h3xGbjz+1VkoXZGDmQOfUqU63kjU+Foe3Z1bFakTZYcjJ7sHTFJoqeM4LVqiwFwD1jIaNgxbKdLhq+37HFLc42AkLnfhAW48mRlvtIAzI+ywactbUhj9fHbljNRn0OyKCWU2mhwBTxoWOyB4qf7yoFLlJvxogUmVQJlKVg9+ivTeITRXdaMXPoMZV2+vLYiNl/8iXHqGKeBgBi/mpNxSoerw29v+W7MXx2uhsC40WWLJv/k/AxGYos+HmIAmSfhOs1kFOBzcI25l2M31RQrptj9lM+5aoLb2MjI8qNorCwwxlvRkTp8mEAI9XXYbAXybbxqcEiUwslzyEutTvv0ZSjBBX9LBfK9Y7lp//Ainwm9saHMnl7wrbqjc3dngGAqHS78OqFK7E5CAjtiUXUqsfenYEYoYmN3wX9eqKRXl8HcxJu0vv5BT1Vwm0YntmcS9IbvY1S5R8vW32iHBOKp9bcBF6Ujrp1xFP94GEsYb77b3MglehiItHqp1yRq3N39TJhK3Pv51LLo/dwhM+hruyBZmgulgjOz51EaN9kjzdDHtXwUsfVuViGGAD7gHCPwMNK0G2sL8/3nubKyUDXvcdJAACtR03tl2WyEVVH0HrzB0PvCD1WuWGTXjE4zuTqPssiiQyQ68O6NgrD45IU/wlrWL+0s2hegPgCFvYHF+HB+GCt/MNk0I8vgNdsnd/nM/BX77TRbMeQhAGdhgbGGPLhy8nH00qAX99vUOnZokGdkNEPn4l7Sve1xRIQvmzjAOcE1qEM5XVZlzlI4LhDWb1bmbmxfIteqcTQuyDIyyJ2VX3sIZ72vuKGWYLNKeFXOh5Kvw7fR0QPIz87/aIieCnGIFwLF5/CurahesQn3DTIEMpCTktZH+UglDAO4aOf+mx8LYyfwCZYBQFuuJ3zTJMtHD5Fsezqr3zJEWBLn8+0Gmaf/IjK4GlYQgQYgjp2VI4aC6T2+4XuBZTSDGy3O+u4bp+gxKYpUDWsX/d9dhQOiomicqM8hoi4CgpJmgEoYkFijcwBZqO1CIds55BfU5k4mvui7Vq94gHcvrN6xbfSlat23NQqVzqQQF0IXVdS9NKcUHIBmgaMBEo5xp4cYOoBKeJlaXhcVJjAwgYFR6k0RNfJeTz/6xn/KBLIF/gpzKGlW20tTgGUbtf1PyoKH0lSqrF5b02n3LDq3hEHLrB77pF2YWJadK8RmcgtjKhEOWoF111gZE7ozK6pqxP7qDoraKFPcHWliaGOckuANHX6+JNglk8pqI/naZVCgaBK9Hz1cDr9NEXS46PObk6syaedqtG4Z/SYIS9WxQqDgT+Yw0m8RrFNlJdaYUcuTMQ6OgxVKZZHCpvx6aTD8UdZQW49gnm1jai+rp2ksQuqZXI1caH0hxJ+oGNS8nsGaqJBLb2f60ePHZIHv6tKGnSEGJHHGidP19qA+lUX4BFXomQ3PTmoG5NLxTASfHEDbEoQb0F8l9qfx0z2IugrEV/B7QrqICREBLIyg0LskGHscV52QeDOU5Pey/+NY0uEskC5uoUDt6DfKcQLPj5eIcwj+iyE3CCXeP33vtT08yV+ApLSouV5ZJGXPQVhCkXazrMNbu0TvO13Xfgi8BRj3ZAfumMxYx7H4/bhnxDWgYUJcFGj955oBwEMs/1Re9W+JYWpCUnHbBf8WXdPK59pampktU/JaHpzP//lFoso=
    env:
      aws-access:
        AWS_REGION: sealed_version_of_the_base64_encoded_aws_region
        AWS_ACCESS_ID: sealed_version_of_the_base64_encoded_aws_access_id
      database-url:
        DATABASE_URL: sealed_version_of_the_base64_encoded_database_url
  global:
    environment: STAGING
    image:
      repository: quay.io/uxi/aruba-uxi-example
      pullPolicy: Always
    env:
      DEBUG: false
    envFields:
      HOST_IP: status.hostIP
    labels:
      global-label: global-label
  applications:
    example-service:
      role: webapp
      revisionHistoryLimit: 4
      replicaCount: 2
      image:
        tag: 1.0.1
      serviceAccount:
        create: true
      port: 8000
      livenessProbe:
        path: /livez
      readinessProbe:
        path: /readyz
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
      configMap:
        annotations: {}
        readOnly: false
        path: /app/config
        data:
          config.json: |
            {
              foo: bar
              bing: bang
              server: {
                host: hostname
              }
            }
      secretMount:
      - name: firebase-service-account
        readOnly: true
        path: /app/resources
      env:
        AWS_DEFAULT_REGION: us-west-1
      envSealedSecrets:
        database-url:
          - DATABASE_URL
        aws-access:
          - AWS_REGION
          - AWS_ACCESS_ID
      datadog:
        enabled: true
        traceEnabled: true
      sentry:
        enabled: true
        dsn: sealed_version_of_the_base64_encoded_example_service_sentry_dsn
      labels:
        example-service-staging: example-service-staging
      ingress:
        enabled: true
        hosts:
        - host: example-service.local
          paths:
            - path: /
    example-worker:
      role: worker
      command: ["echo", "foo bar biz"]
      datadog:
        enabled: true
  cronjobs:
    example-cronjob-producer:
      schedule: "*/10 * * * *"
      suspend: true
      command: ["run-kinesis", "producer"]
      serviceAccount:
        create: true
      datadog:
        enabled: true
      sentry:
        enabled: true
        dsn: sealed_version_of_the_base64_encoded_example_cronjob_producer_sentry_dsn
    example-cronjob-consumer:
      schedule: "*/5 * * * *"
      command: ["run-kinesis", "consumer"]
      restartPolicy: Never
      env:
        AWS_ACCESS_ID: uid-12345
      envSealedSecrets:
        aws-access:
          - AWS_REGION
      labels:
        example-cronjob-consumer-staging: example-cronjob-consumer-staging
