{{- range $name, $data := .Values.applications }}
{{- $sealedSecrets := deepCopy (default dict $.Values.global.envSealedSecrets) | mustMerge (default dict $data.envSealedSecrets) }}
{{- range $secretName, $secretData := $sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealedSecret.name" (dict "name" $name "secretName" $secretName)}}
  labels:
    {{- include "asimmetric.labels" (dict "context" $ "name" $name) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $secretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end }}
{{- end }}
