{{- range $name, $data := .Values.cronjobs }}
{{- $serviceAccount := default dict $data.serviceAccount }}
{{- if $serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccount.name" (dict "name" $name "data" $data) }}
  labels:
    {{- include "asimmetric.labels" (dict "context" $ "name" $name) | nindent 4 }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
