{{- if .Values.global.sealedImagePullSecret -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-image-pull-secret
  labels:
    {{- include "application.labels" (dict "context" . "appData" (dict "name" "sealed-image-pull-secret")) | nindent 4 }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.global.sealedImagePullSecret }}
  template:
    data: null
    metadata:
      name: sealed-image-pull-secret
      labels:
        {{- include "application.labels" (dict "context" . "appData" (dict "name" "sealed-image-pull-secret")) | nindent 6 }}
    type: kubernetes.io/dockerconfigjson
{{- end -}}
