{{- if .Values.global.sealedImagePullSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealedImagePullSecret.name" "" }}
  labels:
    {{- include "sealedImagePullSecret.labels" (dict "context" .) | nindent 4 }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.global.sealedImagePullSecret }}
  template:
    data: null
    metadata:
      name: {{ include "sealedImagePullSecret.name" "" }}
      labels:
        {{- include "sealedImagePullSecret.labels" (dict "context" .) | nindent 6 }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
