{{- $sealedSecrets := default dict .Values.sealedSecrets }}
{{- if $sealedSecrets.imagePullSecret }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealedImagePullSecret.name" (dict) }}
  labels:
    {{- include "sealedImagePullSecret.labels" (dict "context" .) | nindent 4 }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.sealedSecrets.imagePullSecret }}
  template:
    data: null
    metadata:
      name: {{ include "sealedImagePullSecret.name" (dict) }}
      labels:
        {{- include "sealedImagePullSecret.labels" (dict "context" .) | nindent 6 }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
