{{- range $appData := .Values.applications }}
{{- $sealedSecrets := mustMergeOverwrite $.Values.global.envSealedSecrets $appData.envSealedSecrets -}}
{{- range $secretName, $secretData := $sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealedSecret.name" (dict "context" $ "appData" $appData "secretName" $secretName)}}
  labels:
    {{- include "sealedSecret.labels" (dict "context" $ "appData" $appData) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $secretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end -}}
{{- end -}}
