{{- range $sealedSecretName, $sealedSecretData := .Values.sealedSecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $sealedSecretName }}
  labels:
    {{- include "asimmetric.labels" (dict "context" $ "name" $sealedSecretName) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $sealedSecretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end }}
