{{ range $appName, $appData := .Values.applications }}
{{- $sealedSecrets := mustMergeOverwrite $.Values.global.envSealedSecrets (default dict $appData.envSealedSecrets) -}}
{{ range $secretName, $secretData := $sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "sealedSecret.name" (dict "context" $ "appName" $appName "secretName" $secretName)}}
  labels:
    {{- include "application.labels" (dict "context" $ "name" $appName) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $secretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
---
{{ end }}
{{ end }}
