{{ range $appName, $appData := .Values.applications }}
{{ if ne $appData.role "worker" }}
{{- $service := $appData.service | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  labels:
    {{- include "application.labels" (dict "context" $ "name" $appName) | nindent 4 }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ $service.port | default 80 }}
      protocol: TCP
      targetPort: http
  selector:
    app: {{ $appName }}
---
{{ end }}
{{ end }}
