{{- range $name, $data := .Values.applications }}
{{- $serviceAccount := $data.serviceAccount | default dict }}
{{- if $serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "serviceAccount.name" (dict "context" $ "name" $name "data" $data) }}
  labels:
    {{- include "application.labels" (dict "context" $ "name" $name) | nindent 4 }}
  {{- with $serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
