{{- range $name, $data := .Values.applications }}
{{- if mustHas $data.role (list "webapp") }}
{{- $service := default dict $data.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "application.labels" (dict "context" $ "name" $name) | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $service.type }}
  ports:
    - name: http
      port: {{ default 80 $service.port }}
      protocol: TCP
      targetPort: http
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}
