{{- range $name, $data := .Values.applications }}
{{- $additionalLabels := deepCopy (default dict $.Values.global.labels) | mustMerge (default dict $data.labels) }}
{{- $configMaps := default dict $data.configMap }}
{{- range $configMap := $configMaps}}
{{- if $configMap.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $name "additionalLabels" $additionalLabels) | nindent 4 }}
  {{- with $configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data: {{- toYaml $configMap.data | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
