{{- range $name, $data := .Values.applications }}
{{- $ingress := default dict $data.ingress }}
{{- $svcPort := $data.port }}
{{- $service := default dict $data.service }}
{{- $useLegacyApiVersion := default false $ingress.useLegacyApiVersion }}
{{- $additionalLabels := deepCopy (default dict $.Values.global.labels) | mustMerge (default dict $data.labels) }}
{{- if $ingress -}}
{{- if $useLegacyApiVersion }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $name "additionalLabels" $additionalLabels) | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range $ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range $path := .paths }}
      - path: {{ $path.path }}
        backend:
          {{- if $path.backend }}
          serviceName: {{ default $name $path.backend.serviceName }}
          servicePort: {{ default 80 $path.backend.servicePort }}
          {{- else }}
          serviceName: {{ $name }}
          servicePort: {{ default 80 $service.port }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $name "additionalLabels" $additionalLabels) | nindent 4 }}
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ingress.className }}
  {{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  {{- range $ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range $path := .paths }}
      - path: {{ $path.path }}
        pathType: {{ default "ImplementationSpecific" $path.type }}
        backend:
          {{- if $path.backend }}
          service:
            name: {{ default $name $path.backend.serviceName }}
            port:
              number: {{ default 80 $path.backend.servicePort }}
          {{- else }}
          service:
            name: {{ $name }}
            port:
              number: {{ default 80 $service.port }}
          {{- end }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
