{{- range $name, $data := .Values.cronjobs }}
{{- $sealedSecrets := default dict $.Values.sealedSecrets }}
{{- $overrideImage := default dict $data.image }}
{{- $datadog := default dict $data.datadog }}
{{- $sentry := default dict $data.sentry }}
{{- $envBasic := deepCopy (default dict $.Values.global.env) | mustMerge (default dict $data.env) }}
{{- $envFields := deepCopy (default dict $.Values.global.envFields) | mustMerge (default dict $data.envFields) }}
{{- $envSealedSecrets := $data.envSealedSecrets }}
{{- $additionalLabels := deepCopy (default dict $.Values.global.labels) | mustMerge (default dict $data.labels) }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $name }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $name "additionalLabels" $additionalLabels) | nindent 4 }}
spec:
  schedule: {{ $data.schedule | quote }}
  suspend: {{ default false $data.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- if $sealedSecrets.imagePullSecret }}
          imagePullSecrets:
          - name: {{ include "sealedImagePullSecret.name" (dict) }}
          {{- end }}
          {{- if $data.serviceAccount }}
          serviceAccountName: {{ include "serviceAccount.name" (dict "name" $name "data" $data) }}
          {{- end }}
          containers:
          - name: {{ $name }}
            image: {{ include "aruba-uxi.image" (dict "context" $ "data" $overrideImage) }}
            imagePullPolicy: {{ include "aruba-uxi.imagePullPolicy" (dict "context" $ "data" $overrideImage) }}
            env:
            - name: ENVIRONMENT
              value: {{ include "global.environment" (dict "environment" $.Values.global.environment) | quote }}
            - name: DD_ENABLED
              value: {{ default "false" $datadog.enabled | quote }}
            {{- if $datadog.enabled }}
            - name: DD_ENV
              value: {{ include "global.environment" (dict "environment" $.Values.global.environment) | quote  }}
            - name: DD_SERVICE
              value: {{ $name | quote }}
            - name: DD_TRACE_ENABLED
              value: {{ default "false" $datadog.traceEnabled | quote }}
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENTITY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            {{- end }}
            {{- if $sentry.enabled }}
            - name: SENTRY_ENVIRONMENT
              value: {{ include "global.environment" (dict "environment" $.Values.global.environment) | quote }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ template "sealedSentryDsn.name" (dict "name" $name) }}
                  key: SENTRY_DSN
            {{- end }}
            {{- if or $envBasic $envFields $envSealedSecrets }}
            {{- include "aruba-uxi.env-variables" (dict "data" $envBasic) | indent 12 }}
            {{- include "aruba-uxi.env-fields" (dict "data" $envFields) | indent 12 }}
            {{- include "aruba-uxi.env-sealed-secrets" (dict "name" $name "data" $envSealedSecrets) | indent 12 }}
            {{- end }}
            {{- with $data.command }}
            command: {{ toRawJson . }}
            {{- end }}
          restartPolicy: {{ default "OnFailure" $data.restartPolicy }}
{{- end }}
