{{- $sealedSecrets := default dict .Values.sealedSecrets }}
{{- range $sealedSecretName, $sealedSecretData := $sealedSecrets.env  }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $sealedSecretName }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $sealedSecretName) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $sealedSecretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end }}
{{- range $sealedSecretName, $sealedSecretData := $sealedSecrets.secretMount  }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $sealedSecretName }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $sealedSecretName) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $sealedSecretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end }}
