{{- $sealedSecrets := default dict .Values.sealedSecrets }}
{{- $sealedSecretDict := deepCopy (default dict $sealedSecrets.secretMount) | mustMerge (default dict $sealedSecrets.env) }}
{{- range $sealedSecretName, $sealedSecretData := $sealedSecretDict  }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $sealedSecretName }}
  labels:
    {{- include "aruba-uxi.labels" (dict "context" $ "name" $sealedSecretName) | nindent 4 }}
spec:
  encryptedData:
    {{- range $secretKey, $secretValue := $sealedSecretData }}
    {{ $secretKey }}: {{ $secretValue }}
    {{- end }}
{{- end }}
