# TODO: could add additional label in each asimmetric
# TODO: add external IP service type
# TODO: add external name service type
asimmetric:
  ## Global values used by all manifests
  ##
  global:
    ## Configures the labels for all manifests
    labels:
      repo: asimmetric-example
    ## Configures the image repository and pull policy for all pods
    ##
    image:
      repository: asimmetric-example
      tag: "1.2.3"
      imagePullPolicy: IfNotPresent
    ## Creates a sealed image pull secret
    ##
    sealedImagePullSecret: sealed_version_of_the_base64_encoded_dockerconfigjson
    ## Basic environment variables (Optional)
    ## If overridden, in application or cronjobs, precedence is given to the overridden values
    ## Default: None
    ##
    env:
      ENVIRONMENT: global-value # DEV|STAGING|PRODUCTION
      OVERRIDDEN_VALUE: global-value
    ## Environment variables set from the deployment fields (Optional)
    ## If overridden, in application or cronjobs, precedence is given to the overridden values
    ## Default: None
    ##
    envFields:
      HOST_IP: global-value
      OVERRIDDEN_FIELD_VALUE: global-value
    ## Environment variables set from sealed secrets (Optional)
    ## If overridden, in application or cronjobs, precedence is given to the overridden values
    ## A sealed secret is created for each envSealedSecrets.<value>
    ## NB! These can be overridden at the secret name level and no lower. 
    ## E.g aws-access can be overridden but you can not define aws-access.AWS_REGION here 
    ## and aws-access.AWS_ACCESS_ID in the pod
    ## You must override the whole sealed secret
    ## Default: None
    ##
    envSealedSecrets:
      overridden-secret:
        OVERRIDDEN_VALUE: global-value
      aws-access:
        AWS_REGION: global-value
        AWS_ACCESS_ID: global-value
  ## Creates one or more applications unique by role.
  ## Roles are one of service|worker
  applications:
    ## Applications are defined as keys in the map
    ## The key is used as the name of the application and subsequent objects created
    ##
    example-service:
      ## Asimmetric application role: service|worker
      ## The difference between a service and worker is the worker does not have ports exposed. 
      ## I.e a worker does not get a Service manifest defined
      ##
      role: service
      ## Sets the replica count (Optional)
      ## Default: 1
      ##
      replicaCount: 1
      ## Configures the image and image pull policy (Optional)
      ## Default: uses .global.image
      ##
      image: {}
        # repository: nginx
        # pullPolicy: IfNotPresent
        # tag: ""
      ## Attaches a service account it to the application (Optional)
      ## Default: uses the default service account in the namespace
      ##
      serviceAccount:
        create: true
        # name: service-account-name
        # annotations: {} 
      ## Overrides the command from the dockerfile (Optional)
      ## Default: the Dockerfile command is used
      ##
      command: []
      ## Which port on the pod is exposed.
      ## NB! for 'role: worker' do not set this
      ##
      port: 8000
      ## Configures the service created (Optional)
      ## Default: ClusterIP on port 80
      ##
      service: {}
        # type: ClusterIP
        # port: 80
      ## Enables the liveness probe on the specified path (Optional)
      ## NB! for 'role:worker' this should be excluded
      ##
      livenessProbe:
        path: /livez
      ## Enables the readiness probe on the specified path (Optional)
      ## NB! for 'role:worker' this should be excluded
      ##
      readinessProbe:
        path: /readyz
      ## Configure the pod resources (Optional)
      ## Default: lets kubernetes set the resources
      ##
      resources: {}
        # limits:
        #   cpu: 100m
        #   memory: 256Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi
      ## Configures the node selectors for the pods (Optional)
      ## Default: None
      ##
      nodeSelector: {}
      ## Configures the tolerations for the pods (Optional)
      ## Default: None
      ##
      tolerations: []
      ## Configures the pod affinity for the pods (Optional)
      ## Default: None
      ##
      affinity: {}
      ## Adds a config map to the application (Optional)
      ## Default: None
      ###
      configMap:
        annotations: {}
        readOnly: false
        path: /app/config
        data:
          config.json: |
            {
              foo: bar
              bing: bang
              server: {
                host: hostname
              }
            }
      ## Environment variables set from provided key:value pair (Optional)
      ## If overridden, in application or cronjobs, precedence is given to the overridden values
      ## Default: None
      ##
      env:
        AWS_DEFAULT_REGION: example-service
        OVERRIDDEN_VALUE: example-service
      ## Environment variables set from the deployment fields (Optional)
      ## If overridden, in application or cronjobs, precedence is given to the overridden values
      ## Default: None
      ##
      envFields:
        HOST_IP: example-service
        OVERRIDDEN_FIELD_VALUE: example-service
      ## Environment variables set from sealed secrets (Optional)
      ## If overridden, in application or cronjobs, precedence is given to the overridden values
      ## A sealed secret is created for each envSealedSecrets.<value>
      ## Default: None
      ##
      envSealedSecrets:
        overridden-secret:
          OVERRIDDEN_VALUE: example-service
        database-url:
          DATABASE_URL: example-service
    example-worker:
      role: worker
      env:
        AWS_DEFAULT_REGION: example-worker
        OVERRIDDEN_VALUE: example-worker
      command: ["echo", "foo bar biz"]
      serviceAccount:
        create: true
      configMap:
        annotations: {}
        path: /app/config
        data:
          config.json: |
            "hello config map"
  cronjobs:
    example-cronjob-echo:
      schedule: "*/5 * * * *"
      command: ["echo", "foo bar biz"]
      restartPolicy: Never
      env:
        AWS_DEFAULT_REGION: example-cronjob-echo
        OVERRIDDEN_VALUE: example-cronjob-echo
      envSealedSecrets:
        overridden-secret:
          OVERRIDDEN_VALUE: example-cronjob-echo
        database-url:
          DATABASE_URL: example-cronjob-echo
    example-cronjob-kinesis-consumer:
      schedule: "*/5 * * * *"
      command: ["run-kinesis"]
      restartPolicy: Never
      env:
        AWS_DEFAULT_REGION: example-cronjob-kinesis-consumer
        OVERRIDDEN_VALUE: example-cronjob-kinesis-consumer
      envSealedSecrets:
        overridden-secret:
          OVERRIDDEN_VALUE: example-cronjob-kinesis-consumer
        database-url:
          DATABASE_URL: example-cronjob-kinesis-consumer
