---
# Source: jobexample/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: busybox:latest
        imagePullPolicy: Never
        command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
        env:        
        - name: CAPE_ROLE
          value: "STAGING"                                
        - name: HOST_IP
          valueFrom:
           fieldRef:
             fieldPath: status.hostIP        
        resources:
          limits:
            cpu: 10m
            memory: 200Mi
      restartPolicy: OnFailure
---
# Source: jobexample/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-with-timeout
spec:
  template:
    metadata:
      name: pi-with-timeout
    spec:
      containers:
      - name: pi-with-timeout
        image: ubuntu
        imagePullPolicy: Always
        command: ["perl","-Mbignum=bpi","-wle","print bpi(2000)"]
        env:        
        - name: CAPE_ROLE
          value: "STAGING"        
        - name: DEBUG
          value: "false"                        
        - name: HOST_IP
          valueFrom:
           fieldRef:
             fieldPath: status.hostIP        
        resources:
          limits:
            cpu: 10m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /app/config.json
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: myconfig
