---
# Source: serviceexample/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: serviceexample
  labels:
    name: serviceexample
    app: serviceexample
    repo: chart-library
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: serviceexample
