apiVersion: v2
name: deploymentlib
description: A Helm chart library for application deployments
type: library
version: 0.6.1
appVersion: "1.16.0"
dependencies:
- name: podlib
  version: "*"
  repository: "file://../../charts/podlib"
