name: Lint and Test Charts

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Template deployment
        run: just template-deployment

      - name: Template deployment with values
        run: just template-deployment -f charts/deploymentexample/values.yaml -f charts/deploymentexample/values-staging.yaml

      - name: Template ingress
        run: just template-ingress

      - name: Template ingress with values
        run: just template-ingress -f charts/ingressexample/values.yaml -f charts/ingressexample/values-staging.yaml

      - name: Template job
        run: just template-job

      - name: Template job with values
        run: just template-job -f charts/jobexample/values.yaml -f charts/jobexample/values-staging.yaml

      - name: Template service
        run: just template-service

      - name: Template service with values
        run: just template-service -f charts/serviceexample/values.yaml -f charts/serviceexample/values-staging.yaml

      - name: Template serviceaccount
        run: just template-serviceaccount

      - name: Template serviceaccount with values
        run: just template-serviceaccount -f charts/serviceaccountexample/values.yaml -f charts/serviceaccountexample/values-staging.yaml
