name: Lint and Test Charts

on: [push]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: extractions/setup-just@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Template Check
        run: |
          just output
          git diff --exit-code -- examples/asimmetric-example/output.yaml
